force-app/main/default/objects/dtmRutaIntegracion__mdt/dtmRutaIntegracion__mdt.object-meta.xml
<CustomObject>
    <label>Ruta Integracion</label>
    <pluralLabel>Ruta Integracion</pluralLabel>
</CustomObject>

force-app/main/default/objects/dtmRutaIntegracion__mdt/fields/dtmEndpoint__c.field-meta.xml
<CustomField>
    <fullName>dtmEndpoint__c</fullName>
    <label>Endpoint</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/dtmUtility.cls
public class dtmUtility {
    public static final String BAD_REQUEST_MSJ = 'JSON MALFORMADO: ESPERADO ';
    public static final String INTERNAL_ERROR_MSJ = 'ERROR INTERNO ';
    public static final Integer BAD_REQUEST_CODE = 400;
    public static final Integer INTERNAL_ERROR_CODE = 500;
    
    public static String getEndpoint(String nombreURL){
        try{
            dtmRutaIntegracion__mdt ruta = dtmRutaIntegracion__mdt.getInstance(nombreURL); 
            return ruta.dtmEndpoint__c;
        }catch(Exception ex){
            return null;
        }
    } 
}